version: "3.7"

services:
  fastapi:
    # image: fastapi
    build: .
      # context: .
      # dockerfile: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    volumes:
      - ./app:/code/app
