version: "3.7"

services:
  fastapi:
    # image: fastapi
    build:
      .
      # context: .
      # dockerfile: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 2080:80
    volumes:
      - ./app-stable:/code/app
    depends_on:
      - db
    networks:
      - fastnet

  db:
    image: mariadb:10
    restart: always
    ports:
      - 33062:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - fastnet

networks:
  fastnet:
    driver: bridge
