version: "3.7"

services:
  fastapi:
    # image: fastapi
    build: .
      # context: .
      # dockerfile: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    volumes:
      - ./app:/code/app
    environment:
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_USER: root
      MONGODB_PASS: 1234
      MONGODB_DB: itoktok
      MONGODB_URL: mongodb://root:1234@mongo:27017/itoktok
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
