version: "3.7"

services:
  fastapi:
    # image: fastapi
    build: .
      # context: .
      # dockerfile: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 2080:80
    volumes:
      - ./app-stable:/code/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "33062:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    env_file: .env

networks:
  fastnet:
    driver: bridge
